always explicitly decode UTF-8
otherwise decode() on Python2 will default to ASCII and thus we end up
with errors like this:

    ERROR: unhandled exception occurred:
    Traceback (most recent call last):
      File "/bin/katello-ssl-tool", line 51, in <module>
        sys.exit(mod.main() or 0)
      File "/usr/lib/python2.7/site-packages/katello_certs_tools/katello_ssl_tool.py", line 1102, in main
        ret = _main() or 0
      File "/usr/lib/python2.7/site-packages/katello_certs_tools/katello_ssl_tool.py", line 1050, in _main
        genCaRpm(DEFS, options.verbose)
      File "/usr/lib/python2.7/site-packages/katello_certs_tools/katello_ssl_tool.py", line 665, in genCaRpm
        out = out_stream.read().decode()
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 73: ordinal not in range(128)